server:
  port: 5174

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/twitter_clone
    username: root
    password: yenoshdulla
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
